### ISSUE TITLE
how i use it

### ISSUE THREAD

**Issue by Eduardo7881** [ultra0000/tv2emu#3]

**Comment by amrd24** [comment]
that's the neat thing
you don't

**Comment by TheMsntv2Guy** [comment]
I'M THE REAL NUMERO UNO

**Comment by SKCro** [comment]
You'd have to compile the source code yourself. **Even if you did, _it still won't work_ because the emulation is incomplete (and has been for a while).** We haven't even gotten it to _boot_, let alone output video or allow for keyboard control. Even after that, we still have the problem of getting a server running for it.

**Comment by Flamelord626** [comment]
lmao the shittertin cant msntv2 bro is dieing inside fr fr bro cant live without his msntv2

**Comment by sudodebian** [comment]
funnily thing, you don't, this emu is not even in the state of booting the shitter
